### ISSUE TITLE
Slides

### ISSUE THREAD

**Issue by shiffman** [ITPNYU/ITP-IMA-Community-Guidelines#34]
There are now slides to go along with the CoC for orientation. Some design elements and colors are borrowed from The Coding Train and ml5.js, however, we may ultimately want to have a custom design language for the ITP/IMA CoC itself. 

![ITP IMA  Code of Conduct](https://user-images.githubusercontent.com/191758/90944420-99c78c00-e3ec-11ea-8a50-1735512a441f.png)

Here are the slides:
https://docs.google.com/presentation/d/1uV7DVr6Z0ZVw8tjH4C7xfNkpr_IKfijUaRTWne6tSOo/edit?usp=sharing

Should we link to these in the repo and/or use any of the design elements?

**Comment by shiffman** [comment]
@themiscadiz is there a place on the website where it would make sense to link to this material?

**Comment by themiscadiz** [comment]
@shiffman I'll add a section in the Get Involved page about additional material.

**Comment by shiffman** [comment]
We can track any additional resources and slides that we may want to consider in the next session in #51
