### ISSUE TITLE
Technology / Networks as related to Land Acknowledgement

### ISSUE THREAD

**Issue by bezark** [ITPNYU/ITP-IMA-Community-Guidelines#37]
Hello! Not sure if this is the proper method for contributing to the CoC (I’m new on the scene!) but I thought it could be exciting to also try and include the land that all servers we use at itp are located on in the land acknowledgment. I think Discord servers are in NYC (probably financial district?) and I’m not sure where zoom servers are or what other servers ITP relies on. It’s really easy to think of the internet as this magical thing that floats above history, but it is definitely made of very physical objects that are also located on stolen land!

**Comment by shiffman** [comment]
Yes, this is exactly the right way to contribute, yay!!! This is a great suggestion and @tigoe's research and work on the Understanding Networks course could be a good resource for us! We haven't fully defined a process for community additions, edits, etc. but feel free to propose any ideas in this thread or stay tuned for maybe a virtual co-writing / discussion session!

**Comment by bezark** [comment]
Neat! I'll definitely stay tuned.  For now I'll watch the repository and if I think of anything I'll be sure to post it!

**Comment by shiffman** [comment]
@bezark It's been almost a year since this discussion thank you for your patience! Stay tuned for an announcement about a CoC github session on April 16th!

**Comment by shiffman** [comment]
The Land Acknowledgement has been updated with #59, even though it's been many years I will continue to leave this issue open as I think it's an important discussion related to how this document can be more specific to the research and creative practices at ITP/IMA.
